version: "3.8"
services:
  controller:
    build: .
    container_name: autolimit_controller
    environment:
      - TZ=Asia/Shanghai
      # FLASK_ENV=development # 取消注释以开启Debug模式
    volumes:
      - ./data:/app/data # 将主机上的data目录映射到容器内的data目录
    ports:
      - "9190:9190"
    restart: unless-stopped

networks: {} 